HTTP/1.0 501 NOT IMPLEMENTED
Content-Length: 46
Content-Type: application/json
Date: Fri, 20 Mar 2015 14:41:01 GMT
Server: Werkzeug/0.10.1 Python/2.7.8+

{
    "message": "Web service not implemented"
}