POST /api/v0.1/get_packages HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 60
Content-Type: application/json
Host: localhost:19021
User-Agent: HTTPie/0.9.2